// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhP9L4Xys1yMb_ptGgMZnV0-Ocm4tpQbM',
    appId: '1:73429866591:web:97966ef00e254e88fa23ea',
    messagingSenderId: '73429866591',
    projectId: 'kutuphaneotomasyon-1d75d',
    authDomain: 'kutuphaneotomasyon-1d75d.firebaseapp.com',
    storageBucket: 'kutuphaneotomasyon-1d75d.appspot.com',
    measurementId: 'G-0XED9EEGZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpgFVP7AuLRz7ExruVyHiQXxwmIEDbEAM',
    appId: '1:73429866591:android:ca6c886d714bf541fa23ea',
    messagingSenderId: '73429866591',
    projectId: 'kutuphaneotomasyon-1d75d',
    storageBucket: 'kutuphaneotomasyon-1d75d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ7Ys2mmDUgdkMKixjvx3WhnCcrU9WlfA',
    appId: '1:73429866591:ios:cc46497fb6df7cb0fa23ea',
    messagingSenderId: '73429866591',
    projectId: 'kutuphaneotomasyon-1d75d',
    storageBucket: 'kutuphaneotomasyon-1d75d.appspot.com',
    iosBundleId: 'com.example.kutuphaneOtomasyon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ7Ys2mmDUgdkMKixjvx3WhnCcrU9WlfA',
    appId: '1:73429866591:ios:0e470f5313017927fa23ea',
    messagingSenderId: '73429866591',
    projectId: 'kutuphaneotomasyon-1d75d',
    storageBucket: 'kutuphaneotomasyon-1d75d.appspot.com',
    iosBundleId: 'com.example.kutuphaneOtomasyon.RunnerTests',
  );
}
